-------------------------------------------------------------------------------
--                                                                           --
--                                  Yolk                                     --
--                                                                           --
--                             Yolk.Syndication                              --
--                                                                           --
--                                  SPEC                                     --
--                                                                           --
--                   Copyright (C) 2010-2011, Thomas Løcke                   --
--                                                                           --
--  Yolk is free software;  you can  redistribute it  and/or modify it under --
--  terms of the  GNU General Public License as published  by the Free Soft- --
--  ware  Foundation;  either version 2,  or (at your option) any later ver- --
--  sion.  Yolk is distributed in the hope that it will be useful, but WITH- --
--  OUT ANY WARRANTY;  without even the  implied warranty of MERCHANTABILITY --
--  or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License --
--  for  more details.  You should have  received  a copy of the GNU General --
--  Public License  distributed with Yolk.  If not, write  to  the  Free     --
--  Software Foundation,  51  Franklin  Street,  Fifth  Floor, Boston,       --
--  MA 02110 - 1301, USA.                                                    --
--                                                                           --
-------------------------------------------------------------------------------

package Yolk.Syndication is

--     function Initialize
--       (Id          : in String;
--        Title       : in String;
--        Base_URI    : in String := None;
--        Encoding    : in String := "utf-8";
--        Language    : in String := None;
--        Title_Kind  : in Content_Kind := Text)
--        return Atom_Feed;
   --  Initialize an Atom object with the _required data_, as per the Atom
   --  specification RFC4287:
   --    http://tools.ietf.org/html/rfc4287
   --
   --  Base_URI:
   --    Establishes base URI for resolving relative references in the feed.
   --    Is overruled by Base_URI parameters for individual feed entries.
   --  Encoding:
   --    The encoding attribute of the root XML element. This package does not
   --    do any kind of encoding/decoding, so make sure that the data you put
   --    in match the encoding given here.
   --  Id:
   --    A permanent, universally unique identifier for the feed.
   --  Language:
   --    Indicated the natural language for the atom:feed element and its
   --    descendents.
   --  Title:
   --    A human-readable title for the feed.
   --  Title_Kind:
   --    The title kind. See Content_Type.

end Yolk.Syndication;
